name: Party Safari
favicon: null
layout_spectrum: 0.79412
typography_spectrum: 0.73019
title: Kids Parties
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.26542597520165145
  rhythmicContrast: 0.25
purpose: []
